name: 'planetkart_dw'
version: '1.0.0'
config-version: 2

profile: 'planetkart_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  planetkart_dw:
    staging:
      +schema: STAGE
      +materialized: view
    marts:
      +schema: ANALYTICS
      +materialized: table

snapshots:
  planetkart_dw:
    +target_schema: PLANETKART_ANALYTICS
